<?php

/**
 * GramaticaTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class GramaticaTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object GramaticaTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Gramatica');
    }
		
		public function getByNameInLevel($level, $name) {
			return $this->createQuery('a')->where('a.nombre = ?', $name)->andwhere('a.nivel = ?', $level)->execute();
		}
		
		public function getAll() {
      return $this->createQuery('a');
		}
		
		public function getAllByLevel() {
      $result = array();
      $result[] = array();
      $todos = $this->createQuery('a')->execute();
      foreach($todos as $uno) {
        $guardar = true;
        $nombre = $uno->getNombre();
        $nivel = $uno->getNivel();
        foreach ($result as $guardados) {
          foreach($guardados as $guardado) {
            if ($guardado == $nombre) {
              $guardar = false;
            }
          }
        }
        if ($guardar) {
            $posicion[$nivel] = $nombre;
            $result[$nivel] = $posicion;
          }
      }
      return $result;
		}
		
}
