<?php

/**
 * JuegoTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class JuegoTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object JuegoTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Juego');
    }
}